"""add the rest of tables

Revision ID: ddf4390cff13
Revises: 5196a0af83d4
Create Date: 2023-09-07 23:04:21.373894

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddf4390cff13'
down_revision: Union[str, None] = '5196a0af83d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bookings', ['id'])
    op.add_column('rooms', sa.Column('services', sa.JSON(), nullable=True))
    op.alter_column('rooms', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'rooms', ['id'])
    op.drop_column('rooms', 'service')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('rooms', sa.Column('service', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rooms', type_='unique')
    op.alter_column('rooms', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rooms', 'services')
    op.drop_constraint(None, 'bookings', type_='unique')
    # ### end Alembic commands ###
