[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = 'black'
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.autoflake]
check_diff = true
imports = ['sqlalchemy', 'app']

[tool.pyright]
include = ['app']

[tool.pytest.ini_options]
pythonpath = ". app"
asyncio_mode = "auto"
python_files = ['*_test.py', 'test_*.py', '*_tests.py']
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore:function ham\(\) is deprecated:DeprecationWarning',
]